
class Autogenerated {
  final Albums? albums;

  Autogenerated({this.albums});

  factory Autogenerated.fromJson(Map<String, dynamic> json) {
    return Autogenerated(
      albums: json['albums'] != null ? Albums.fromJson(json['albums']) : null,
    );
  }

  Map<String, dynamic> toJson() => {
        if (albums != null) 'albums': albums!.toJson(),
      };
}

class Albums {
  final String? href;
  final List<Items> items;
  final int? limit;
  final String? next;
  final int? offset;
  final String? previous; // <- FIX: should be String?, not Null
  final int? total;

  Albums({
    this.href,
    this.items = const [],
    this.limit,
    this.next,
    this.offset,
    this.previous,
    this.total,
  });

  factory Albums.fromJson(Map<String, dynamic> json) {
    return Albums(
      href: json['href'] as String?,
      items: (json['items'] as List<dynamic>? ?? const [])
          .map((v) => Items.fromJson(v as Map<String, dynamic>))
          .toList(),
      limit: json['limit'] as int?,
      next: json['next'] as String?,
      offset: json['offset'] as int?,
      previous: json['previous'] as String?, // can be null or url string
      total: json['total'] as int?,
    );
  }

  Map<String, dynamic> toJson() => {
        'href': href,
        'items': items.map((v) => v.toJson()).toList(),
        'limit': limit,
        'next': next,
        'offset': offset,
        'previous': previous,
        'total': total,
      };
}

class Items {
  final String? albumType;
  final List<Artists> artists;
  final List<String> availableMarkets;
  final ExternalUrls? externalUrls;
  final String? href;
  final String? id;
  final List<Images> images;
  final String? name;
  final String? releaseDate;
  final String? releaseDatePrecision;
  final int? totalTracks;
  final String? type;
  final String? uri;

  Items({
    this.albumType,
    this.artists = const [],
    this.availableMarkets = const [],
    this.externalUrls,
    this.href,
    this.id,
    this.images = const [],
    this.name,
    this.releaseDate,
    this.releaseDatePrecision,
    this.totalTracks,
    this.type,
    this.uri,
  });

  factory Items.fromJson(Map<String, dynamic> json) {
    return Items(
      albumType: json['album_type'] as String?,
      artists: (json['artists'] as List<dynamic>? ?? const [])
          .map((v) => Artists.fromJson(v as Map<String, dynamic>))
          .toList(),
      availableMarkets: List<String>.from(json['available_markets'] ?? const []),
      externalUrls: json['external_urls'] != null
          ? ExternalUrls.fromJson(json['external_urls'] as Map<String, dynamic>)
          : null,
      href: json['href'] as String?,
      id: json['id'] as String?,
      images: (json['images'] as List<dynamic>? ?? const [])
          .map((v) => Images.fromJson(v as Map<String, dynamic>))
          .toList(),
      name: json['name'] as String?,
      releaseDate: json['release_date'] as String?,
      releaseDatePrecision: json['release_date_precision'] as String?,
      totalTracks: json['total_tracks'] is int
          ? json['total_tracks'] as int
          : int.tryParse('${json['total_tracks']}'),
      type: json['type'] as String?,
      uri: json['uri'] as String?,
    );
  }

  Map<String, dynamic> toJson() => {
        'album_type': albumType,
        'artists': artists.map((v) => v.toJson()).toList(),
        'available_markets': availableMarkets,
        'external_urls': externalUrls?.toJson(),
        'href': href,
        'id': id,
        'images': images.map((v) => v.toJson()).toList(),
        'name': name,
        'release_date': releaseDate,
        'release_date_precision': releaseDatePrecision,
        'total_tracks': totalTracks,
        'type': type,
        'uri': uri,
      };
}

class Artists {
  final ExternalUrls? externalUrls;
  final String? href;
  final String? id;
  final String? name;
  final String? type;
  final String? uri;

  Artists({
    this.externalUrls,
    this.href,
    this.id,
    this.name,
    this.type,
    this.uri,
  });

  factory Artists.fromJson(Map<String, dynamic> json) {
    return Artists(
      externalUrls: json['external_urls'] != null
          ? ExternalUrls.fromJson(json['external_urls'] as Map<String, dynamic>)
          : null,
      href: json['href'] as String?,
      id: json['id'] as String?,
      name: json['name'] as String?,
      type: json['type'] as String?,
      uri: json['uri'] as String?,
    );
  }

  Map<String, dynamic> toJson() => {
        if (externalUrls != null) 'external_urls': externalUrls!.toJson(),
        'href': href,
        'id': id,
        'name': name,
        'type': type,
        'uri': uri,
      };
}

class ExternalUrls {
  final String? spotify;

  ExternalUrls({this.spotify});

  factory ExternalUrls.fromJson(Map<String, dynamic> json) {
    return ExternalUrls(
      spotify: json['spotify'] as String?,
    );
  }

  Map<String, dynamic> toJson() => {
        'spotify': spotify,
      };
}

class Images {
  final int? height;
  final String? url;
  final int? width;

  Images({this.height, this.url, this.width});

  factory Images.fromJson(Map<String, dynamic> json) {
    return Images(
      height: json['height'] is int ? json['height'] as int : int.tryParse('${json['height']}'),
      url: json['url'] as String?,
      width: json['width'] is int ? json['width'] as int : int.tryParse('${json['width']}'),
    );
  }

  Map<String, dynamic> toJson() => {
        'height': height,
        'url': url,
        'width': width,
      };
}
