// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzUPWQM3dgR8EIos868hD5hpALyw1Ft4E',
    appId: '1:50340198995:web:ac70de61d0746c958664a6',
    messagingSenderId: '50340198995',
    projectId: 'tanit-tanit',
    authDomain: 'tanit-tanit.firebaseapp.com',
    storageBucket: 'tanit-tanit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa0BnWsO1sPQIfm28hcE23AWAoJU2yX-U',
    appId: '1:50340198995:android:75cb7de708e3e60f8664a6',
    messagingSenderId: '50340198995',
    projectId: 'tanit-tanit',
    storageBucket: 'tanit-tanit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjGAuTL1n6tcIjKGz6ZxToH-mRX7ukWDY',
    appId: '1:50340198995:ios:cdde8c800c8d6f578664a6',
    messagingSenderId: '50340198995',
    projectId: 'tanit-tanit',
    storageBucket: 'tanit-tanit.firebasestorage.app',
    iosBundleId: 'com.tanit.tanitTanitApp',
  );

}