import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:http/http.dart' as http;
import 'package:spotify_sdk/spotify_sdk.dart';
import 'package:tanit_tanit_app/app/models/trending_albums.dart';

class SpotifyService {
  static String? _token; // cache token
  static bool _isConnecting = false; // lock to prevent double call
  static Future<String> getAccessToken() async {
    if (_token != null) {
      print("✅ Returning cached token");
      return _token!;
    }

    if (_isConnecting) {
      print("⚠️ Already connecting, skipping duplicate call");
      return "";
    }

    try {
      _isConnecting = true;

      final authenticationToken = await SpotifySdk.getAccessToken(
        clientId: dotenv.env['CLIENT_ID']!,
        redirectUrl: dotenv.env['REDIRECT_URL']!,
        scope:
            'app-remote-control,user-modify-playback-state,playlist-read-private,playlist-modify-public,user-read-currently-playing',
      );

      _token = authenticationToken;
      print("💡 Got a token: $_token");
      return _token!;
    } catch (e) {
      print("💡 error $e");
      return "";
    } finally {
      _isConnecting = false;
    }
  }

  static Future<bool> connectToSpotifyRemote() async {
    try {
      return await SpotifySdk.connectToSpotifyRemote(
        clientId: dotenv.env['CLIENT_ID']!,
        redirectUrl: dotenv.env['REDIRECT_URL']!,
      );
    } catch (e) {
      print("💡 Remote connection error: $e");
      return false;
    }
  }

  // Search albums
  Future<List<dynamic>> searchAlbums(String query) async {
    final token = await getAccessToken();

    final response = await http.get(
      Uri.parse(
        "https://api.spotify.com/v1/search?q=$query&type=album&limit=10",
      ),
      headers: {"Authorization": "Bearer $token"},
    );

    if (response.statusCode == 200) {
      final data = jsonDecode(response.body);
      return data["albums"]["items"];
    } else {
      print("❌ Search failed: ${response.body}");
      return [];
    }
  }

  // Get trending albums (New Releases)
   static Future<Albums?> getNewReleases({
    String country = 'US',
    int limit = 30,
    int offset = 0,
  }) async {
    final token = await getAccessToken();
    if (token.isEmpty) {
      print('❌ No token available');
      return null;
    }

    final uri = Uri.parse(
      'https://api.spotify.com/v1/browse/new-releases'
      '?country=$country&limit=$limit&offset=$offset',
    );

    final res = await http.get(
      uri,
      headers: {'Authorization': 'Bearer $token'},
    );

    if (res.statusCode == 200) {
      final map = jsonDecode(res.body) as Map<String, dynamic>;
      final root = Autogenerated.fromJson(map);
      return root.albums;
    } else {
      print('❌ Failed to get new releases: ${res.statusCode} - ${res.body}');
      return null;
    }
  }

  /// Convenience: returns just the list of Items (albums) for easy UI use.
  static Future<List<Items>> getNewReleaseItems({
    String country = 'US',
    int limit = 30,
    int offset = 0,
  }) async {
    final albums = await getNewReleases(
      country: country,
      limit: limit,
      offset: offset,
    );
    return albums?.items ?? <Items>[];
  }

  Future<Map<String, dynamic>?> getArtist(String artistId) async {
    final token = await getAccessToken();

    final response = await http.get(
      Uri.parse("https://api.spotify.com/v1/artists/$artistId"),
      headers: {"Authorization": "Bearer $token"},
    );

    if (response.statusCode == 200) {
      return jsonDecode(response.body);
    } else {
      print("❌ Failed to get artist: ${response.body}");
      return null;
    }
  }

  // Get single album by ID - NEW METHOD
  Future<Map<String, dynamic>?> getAlbum(String albumId) async {
    try {
      final token = await getAccessToken();

      final response = await http.get(
        Uri.parse('https://api.spotify.com/v1/albums/$albumId'),
        headers: {
          'Authorization': 'Bearer $token',
          'Content-Type': 'application/json',
        },
      );

      if (response.statusCode == 200) {
        final data = json.decode(response.body);
        return data;
      } else {
        print('❌ Failed to get album: ${response.statusCode}');
        print('Response body: ${response.body}');
        return null;
      }
    } catch (e) {
      print('❌ Error getting album: $e');
      return null;
    }
  }

  // Fetch all albums of an artist
  Future<List<Map<String, String>>> getArtistAlbums(String artistId) async {
    final token = await getAccessToken();
    final url = Uri.parse(
      'https://api.spotify.com/v1/artists/$artistId/albums?include_groups=album,single&market=US&limit=50',
    );

    final response = await http.get(
      url,
      headers: {'Authorization': 'Bearer $token'},
    );

    print("Spotify API status code: ${response.statusCode}");
    print("Spotify API response body: ${response.body}");

    if (response.statusCode == 200) {
      final data = jsonDecode(response.body) as Map<String, dynamic>;
      final albums = data['items'] as List<dynamic>;

      // Extract name, image, and id
      final albumsList = albums.map((a) {
        final album = a as Map<String, dynamic>;
        final name = album['name']?.toString() ?? 'Unknown Album';
        final id = album['id']?.toString() ?? '';
        final imageUrl = (album['images'] as List<dynamic>?)?.isNotEmpty == true
            ? album['images'][0]['url'].toString()
            : '';
        return {'id': id, 'name': name, 'image': imageUrl};
      }).toList();

      // Remove duplicates by name
      final uniqueAlbums = {
        for (var a in albumsList) a['name']!: a,
      }.values.toList();

      print("Total albums fetched: ${uniqueAlbums.length}");
      return uniqueAlbums;
    } else {
      print("Failed to fetch albums, status code: ${response.statusCode}");
      return [];
    }
  }

  Future<List<Map<String, String>>> getAlbumTracksWithImages(
    String albumId,
  ) async {
    try {
      final token = await getAccessToken();

      // Fetch basic album tracks
      final url = 'https://api.spotify.com/v1/albums/$albumId/tracks?limit=50';
      final response = await http.get(
        Uri.parse(url),
        headers: {'Authorization': 'Bearer $token'},
      );

      if (response.statusCode != 200) {
        debugPrint("❌Failed to fetch album tracks: ${response.body}");
        return [];
      }

      final data = jsonDecode(response.body);
      final List tracksList = data['items'];

      // Fetch track details individually to get image
      final List<Future<Map<String, String>>> trackFutures = tracksList
          .map<Future<Map<String, String>>>((track) async {
            final trackId = (track['id'] ?? '').toString();
            final trackResponse = await http.get(
              Uri.parse('https://api.spotify.com/v1/tracks/$trackId'),
              headers: {'Authorization': 'Bearer $token'},
            );

            if (trackResponse.statusCode != 200) {
              return {
                'id': trackId,
                'name': (track['name'] ?? '').toString(),
                'duration': (track['duration_ms'] ?? '').toString(),
                'preview_url': (track['preview_url'] ?? '').toString(),
                'image_url': '',
              };
            }

            final trackData = jsonDecode(trackResponse.body);

            final imageUrl =
                (trackData['album']?['images'] as List?)?.isNotEmpty == true
                ? (trackData['album']['images'][0]['url'] ?? '').toString()
                : '';

            return {
              'id': trackId,
              'name': (track['name'] ?? '').toString(),
              'duration': (track['duration_ms'] ?? '').toString(),
              'preview_url': (track['preview_url'] ?? '').toString(),
              'image_url': imageUrl,
            };
          })
          .toList();

      final tracksWithImages = await Future.wait(trackFutures);
      return tracksWithImages;
    } catch (e) {
      debugPrint("❌ Error in getAlbumTracksWithImages: $e");
      return [];
    }
  }

  // Search tracks by keyword
  Future<List<Map<String, String>>> searchTracks(
    String query, {
    int limit = 50,
  }) async {
    final token = await getAccessToken();

    final response = await http.get(
      Uri.parse(
        "https://api.spotify.com/v1/search?q=$query&type=track&limit=$limit",
      ),
      headers: {"Authorization": "Bearer $token"},
    );

    if (response.statusCode == 200) {
      final data = jsonDecode(response.body);
      final tracks = data['tracks']['items'] as List<dynamic>;

      return tracks.map<Map<String, String>>((track) {
        final albumImages = track['album']?['images'] as List<dynamic>?;
        final imageUrl = (albumImages != null && albumImages.isNotEmpty)
            ? albumImages[0]['url']
            : '';

        return {
          'id': track['id'] ?? '',
          'name': track['name'] ?? '',
          'artist': (track['artists'] as List).map((a) => a['name']).join(', '),
          'preview_url': track['preview_url'] ?? '',
          'image_url': imageUrl,
          'duration_ms': (track['duration_ms'] ?? 0).toString(),
        };
      }).toList();
    } else {
      print("❌ Track search failed: ${response.body}");
      return [];
    }
  }
}
